name: Deploy Preview Web Widget

on:
    push:
        branches-ignore:
            - main
    workflow_dispatch:

jobs:
    deploy-preview:
        runs-on: ubuntu-latest
        env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
                check-latest: true

            - name: Setup PNPM
              uses: pnpm/action-setup@v4
              with:
                version: 9

            - name: Cache PNPM Store
              uses: actions/cache@v4
              with:
                path: ~/.pnpm-store
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-pnpm-store-
            - uses: pnpm/action-setup@v4
              with:
                version: 9

            - name: Pull Vercel Production Environment
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Buil Website Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Website Artifacts
              env:
                NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
